Name:           ros-jade-mongo-cxx-driver
Version:        1.0.2
Release:        1%{?dist}
Summary:        ROS mongo_cxx_driver package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://github.com/mongodb/mongo-cxx-driver
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       mongodb
BuildRequires:  boost-devel
BuildRequires:  cmake
BuildRequires:  git
BuildRequires:  python-devel
BuildRequires:  scons

%description
The official C++ client for MongoDB 2.6

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Jun 02 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 1.0.2-1
- Autogenerated by Bloom

* Tue Jun 02 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

